remote_theme: just-the-docs/just-the-docs@v0.5.2

color_scheme: dark
color_scheme_toggle: true

plugins:
  - jekyll-remote-theme

# Enable sidebar navigation
just_the_docs:
  collections:
    your-site:
      output: true
      permalink: /:path/

# Base navigation
nav:
  - title: Home
    url: /

  - title: Combat
    url: /combat/

  - title: Skilling
    url: /skilling/
