remote_theme: just-the-docs/just-the-docs@v0.5.2

color_scheme: dark
color_scheme_toggle: true

plugins:
  - jekyll-remote-theme

nav:
  - title: Home
    url: /
  - title: Combat
    url: /combat
  - title: Skilling
    url: /skilling
