remote_theme: just-the-docs/just-the-docs@v0.5.2

color_scheme: dark
color_scheme_toggle: true

plugins:
  - jekyll-remote-theme

# Enable sidebar navigation
just_the_docs:
  collections:
    your-site:
      output: true
      permalink: /:path/

  # Sidebar behavior
  collapse_navigation: false       # Zorgt dat de zijbalk standaard uitgeklapt is
  navigation_depth: 3              # Toon tot 3 niveaus diep in de zijbalk

# Base navigation
nav:
  - title: Home
    url: /

  - title: Combat
    url: /combat/

  - title: Skilling
    url: /skilling/
